title: foodWeb | Open Source JavaScript Documentation
description: foodWeb is an open source project that makes it simple to access the USDA's Nutrient Standard Reference Database.
show_downloads: true
theme: jekyll-theme-slate
author: Russell Steadman
author_email: e8a7d812@opayq.com